### ISSUE TITLE
Publishing jGreen SNAPSHOT artefacts to a maven repository

### ISSUE THREAD

**Issue by martinstrejc** [martinstrejc/jgreen#15]
# Story
As a **tester** I want to **access jGreen SNAPSHOT release artefacts** in OSS jFrog repository to be able to use a build system such as a Gradle or Maven for the latest dev builds.

# Acceptance Criteria
- jGreen SNAPSHOT artefacts are available in a OSS jFrog
- the maven repository can be any of maven central or other maven style snapshot repository

**Comment by petacz** [comment]
Artifacts published to
https://oss.jfrog.org/list/oss-snapshot-local/cz/wicketstuff/jgreen/jgreen-core/
https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/cz/wicketstuff/jgreen/jgreen-core
